### ISSUE TITLE
Describe difference between before request hooks

### ISSUE THREAD

**Issue by rngtng** [httpyac/httpyac.github.io#15]
I was a bit confused with the two different  before request hooks `{{+ ... }}` and `{{+request ... }}`. I first understood they are the same, but later figured that the first is executed before the request declaration is parsed, the second after. Am I right? Maybe a small diagrams helps understanding. Happy to support here...

**Comment by rngtng** [comment]
Oh and i just figured `{{+response .. }}` happens to a different time (earlier?) as `api.hooks.onResponse.addHook(...` is called. what's the equivalent `api.hooks` for `+response`?

**Comment by AnWeber** [comment]
[onResponseHook](https://github.com/AnWeber/httpyac/blob/main/src/models/httpFileHooks.ts#L18) The Hooks API directly exposes the hooks from [httpFile](https://github.com/AnWeber/httpyac/blob/main/src/store/httpFileStore.ts#L187). 
At the moment, for `{+response ... }}` is still used the hooks of the [HttpRegion](https://github.com/AnWeber/httpyac/blob/main/src/parser/javascriptHttpRegionParser.ts#L116) which are executed [before the HttpFile](https://github.com/AnWeber/httpyac/blob/main/src/utils/requestUtils.ts#L340-L364).  But this is the reason for the bug in AnWeber/httpbook#38.

**Comment by AnWeber** [comment]
I have added a flow chart and extended the event explanation in the scripting. I need to take a look at the easiest way to embed draw.io. Maybe it will be easier for me to draw the steps. Documentation (and Testing) is not my strength. Does it fit for you, you know your way around my code better now?

**Comment by rngtng** [comment]
Yes a good start, I'll have a detailed look. No reason to be humble, I'm still amazed of your efforts in the project as well writing the docs! 

For testing, well this will come.. ;)

**Comment by rngtng** [comment]
Thanks examples helped me a lot. Ironically, the missing one, `parseEndRegion`, does what I'm looking for. Goal was to add syntactic sugar for repetitive httprequest pattern. Simplified example:


```
GIVEME coffee
```

gets transtlateted to

```
POST /v1/giveme/{{globalvar}}/coffee
```

This works with the following hook:

```
api.hooks.parseEndRegion.addHook('prepareRequest', function (context) {
    const request = context.httpRegion.request;

    if (request) {
      const match = request.url.match(/^\s*(?<method>GIVEME) (?<url>[^ ]+)$/ui)?.groups;
      if (match) {
        request.method = 'POST';
        request.url = '/v1/' + match.method.toLowerCase() + '/{{globalvar}}/' + match.url;
      };
    }
  });```

THANKS!

**Comment by AnWeber** [comment]
Yes, I still use the term action for it. Initially I had only an array of classes, which were worked through in order. For those I needed a name => [HttpRegionAction](https://github.com/AnWeber/httpyac/blob/main/src/models/httpRegionAction.ts#L6-L9).  Even the actual specification of the request becomes an action ([httpClientAction](https://github.com/AnWeber/httpyac/blob/main/src/actions/httpClientAction.ts)). This has changed in v3 with the Hooks Api and the objects have basically become functions. 

The functions are processed according to the order in the document, but there are a few exceptions.
* [global httpRegions](https://github.com/AnWeber/httpyac/blob/main/src/utils/httpRegionUtils.ts#L174-L176) are [processed first](https://github.com/AnWeber/httpyac/blob/main/src/httpYacApi.ts#L25-L26)
* Scripts with event specification are removed from the sequence and bound to the respective event. The position of the script is therefore irrelevant, unless there are several in one httpRegion. Before the request, events of `httpFile` are processed before `httpRegion`, after the request `httpRegion` is processed before `httpFile`.

I would now expect the following sequence without trying
```
3 {{}}
1 {{@request}} from global
3 {{@request}}
4 {{@response}}
6 {{@response}} from global
5 {{}}
```

**Comment by rngtng** [comment]
Thx. FYI I did some more structured tests here:  https://gist.github.com/rngtng/415c1d7005bc3b81f02b219d2d1cadd1

Interesting take aways:
 - `@after` is always executed after local script. as well as `response`, but before(?) `request` event?
 - After response,  local event (`@`) exec before global (`+`), except for `responseLogging`
 - Global `+after` is exec before `responseLogging` (expected after)
 - Actions logs are not in realtime -> all output only after the request, except the global.
 - `response` variable is set for the following request. Compare all vs. single response2 run (bug?)

Overall no major surprised but gave me more insights as gained from the docs.

**Comment by rngtng** [comment]
would be interesting to bring in the plugin hooks too. But am I right to say:

* `@request` is same as `OnRequest` Hook
* `@response` is same as `OnResponse` Hook
* `@responseLogging ` is same as `ResponseLogging` Hook

**Comment by AnWeber** [comment]
> @request is same as

I actually only created the script events (@request, @response, @responseLogging) because I had the hooks the same way. It wasn't quite meant to be, but had a feeling it could be handy. Therefore yes, they are definitely identical

> Actions logs are not in realtime -> all output only after the request, except the global.

It was created for the CLI option `filter=onlyFailed`. See for more information AnWeber/httpyac#49. I [intercept all calls to `console`](https://github.com/AnWeber/httpyac/blob/main/src/utils/httpRegionUtils.ts#L46) and [flush](https://github.com/AnWeber/httpyac/blob/main/src/utils/httpRegionUtils.ts#L81) it after request. By this I can [control output of tests](https://github.com/AnWeber/httpyac/blob/main/src/cli/send/send.ts#L113).

> @after is always executed after local script. as well as response, but before(?) request event?
> Global +after is exec before responseLogging (expected after)

I don't understand the order of events here. I know that I need to optimize this. `after` was implemented before the hooks and that is why it is messed up like this. It would make sense to execute after Execute hook, however I don't have that at HttpFile level yet. This is still a work in progress.

> After response, local event (@) exec before global (+), except for responseLogging

I change the order, it seems unexpected.

**Comment by AnWeber** [comment]
I have now added further to the documentation. In addition, the console output is printed directly, unless the `filter=only-failed` setting is set.
