### ISSUE TITLE
Emphasize meaning of `###` and its importance for defining global variables

### ISSUE THREAD

**Issue by myfonj** [httpyac/httpyac.github.io#3]
While all docs examples already involves `###` in all places where "something common for all requests" is in play (as well as between request), there is no explicit description of it's importance for the "global variables" use-case.

Anecdotally, I've recently messed up my `_.http` file and accidentally switched first command separator (or how the `###` should be called) to plain inline comment, like

```
@variable=example
// req 1
http://{{variable}}.org/
### req 2
http://{{variable}}.org/
```

and even switching to "RFC 7230 Request line format" and removing comments altogether

```
@variable=example

GET http://{{variable}}.org/ HTTP/1.1

GET http://{{variable}}.org/ HTTP/1.1
```

and hunted considerable amount of time for why the heck the `variable` is not defined in the second request.  (I know, silly me, indeed changing `// req 1` to `### req 1` or just adding `###` after variable declaration fixed the issue.

Maybe dedicated paragraph somewhere at the beginning of the docs (probably near [request-separators](https://httpyac.github.io/guide/request.html#request-separators)) could have taught me to understand the format better from the start. (IDK where to put it and how to phrase it ATM, that's why this issue and not MR.)

----

BTW it seems that using JS reserved words for variable names (like `@var=...` or `@const=...`) breaks calls on invocation.

----

Anyway, thanks for the great extension, IMO best of it's kind!

**Comment by AnWeber** [comment]
Good suggestion. I actually wanted to explain the functions step by step in the documentation, but since they are often intertwined, it was difficult to implement this.

**Comment by AnWeber** [comment]
The variables are interpreted as Javascript and then replaced. Therefore they must not have JS keywords. I have unfortunately overlooked it and prevented only with the request names. issue is created. Thanks

**Comment by AnWeber** [comment]
I have inserted the change. Thanks for the help. I find the references to weaknesses in the documentation great. Since I built it, all the places are clear to me and I do not notice the places that are a black box for user.
