### ISSUE TITLE
No of Requests fired

### ISSUE THREAD

**Issue by shikharpathak** [httpyac/httpyac.github.io#34]
we have an option of firing repeated requests using CLI, but how many time the requests were actually fired is not displayed in the JSON summary or anywhere. It would be great if we can have it somewhere. It would help in Load Testing.

**Comment by AnWeber** [comment]
I will check it. I have used the function so far only to provoke threading issues, the result on the client was not important to me yet.

**Comment by shikharpathak** [comment]
Okk, yeah if you can add that it would be great.
So that just by looking at the summary, rather than checking server logs, I know that how many times a request was fired.

**Comment by AnWeber** [comment]
I just noticed that it can't quite work. I would have put in the output, but in the end the specified number of requests have been called. You just don't know the number when the CLI call is aborted. Maybe it would be interesting to know at the end how many calls were successful and how many failed. I will implement this functionality.
