### ISSUE TITLE
Is it a correct example for @save?

### ISSUE THREAD

**Issue by vuon9** [httpyac/httpyac.github.io#4]
<img width="984" alt="Screenshot 2021-10-06 at 11 27 11 AM" src="https://user-images.githubusercontent.com/3168632/136140673-416c51ad-a8cc-41ab-9ba1-93edee5fbcb9.png">

**Comment by vuon9** [comment]
<img width="887" alt="Screenshot 2021-10-06 at 11 29 53 AM" src="https://user-images.githubusercontent.com/3168632/136140855-d102f62a-0047-4b65-95d4-b09bb7991080.png">
Also related to @save.

I'm a newbie who trying to use this via VSCode extension, just have a read in the page recently. Sorry if I did something wrong here.

**Comment by AnWeber** [comment]
Thanks for the tip. The examples were really not correct. I had apparently only copied the `@name` example and forgotten to adjust it. Thanks
