### ISSUE TITLE
How to use output redirection?

### ISSUE THREAD

**Issue by suhaig** [httpyac/httpyac.github.io#46]
I try to use [output redirection](https://httpyac.github.io/guide/response.html#output-redirection) from the VSCode extension, but I get
a "RequestError: The `GET` method cannot be used with a body" error.

```
GET /{{basePath}}/{{id}}
Authorization: Bearer {{access_token}}

>> ./{{id}}.json
```

What am I doing wrong?
Thanks.

**Comment by AnWeber** [comment]
That actually looks right ([example](https://httpyac.github.io/guide/response.html#output-redirection)). However, no variables are currently allowed and the `{{` prevent [detection for output redirection](https://github.com/AnWeber/httpyac/blob/main/src/plugins/core/parse/outputRedirectionHttpRegionParser.ts#L14). I will add the variable usage and adjust the regex.

**Comment by AnWeber** [comment]
I released a new version of vscode-httpyac, which fixes this error in httpbook. thx
