### ISSUE TITLE
Question: How do I extract data from a decoded JWT - in an example?

### ISSUE THREAD

**Issue by joerg-walter-de** [httpyac/httpyac.github.io#56]
I find this documentation

[https://httpyac.github.io/guide/metaData.html#jwt](https://httpyac.github.io/guide/metaData.html#jwt)

but wasn't able  to make this work. Ho do I access the decoded data.

I have tried this:

```
###
# @name getTestAccountViaAccessToken
# @forceRef createAccessToken
# @no-cookie-jar
GET http://localhost:3000/v1/accounts/persons/{{createAccessToken.accessToken_parsed.accountId}}
Authorization: Bearer {{createAccessToken.accessToken}}
```

While `{{createAccessToken.accessToken}} ` yields the retrieved token `{{createAccessToken.accessToken_parsed.accountId}}` fails although I am seeing `accessToken_parsed` and `accessToken_parsed.accountId` in the result window of `createAccessToken`.

**Comment by AnWeber** [comment]
An error has crept in. Instead of the extended body, the original body is set to the variable. The variable `createAccessTokenResponse.parsedBody.accessToken_parsed` would work currently.
