### ISSUE TITLE
EntryNotFound error

### ISSUE THREAD

**Issue by asampal** [httpyac/httpyac.github.io#59]
I've used httpyac before, but with the latest version of VSCode Insiders I get the following error. I've tried to uninstall/re-install the extension but the error repeats.

![image](https://user-images.githubusercontent.com/281639/201568486-919adde1-6511-4a4d-8db2-dd798f3f55ed.png)

Version: 1.74.0-insider (system setup)
Commit: ef415578d1b1019db585718968a303eeca4b8979
Date: 2022-11-11T05:19:14.666Z
Electron: 19.1.3
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by AnWeber** [comment]
@asampal I could not reproduce your error on my setup. Can you provide an example setup, how to reproduce the error. The error message is too generic, to investigate further. What do you mean with sandboxed? dev container?

**Comment by asampal** [comment]
I'm not sure what sandboxed means - it is part of the details shown in VSCode. I'll try to figure out what is special about the workspace where this happens. In a brand new workspace the error doesn't occur.

**Comment by AnWeber** [comment]
@asampal I don't think sandboxed is the problem at all. Probably [Electron sandboxed](https://www.electronjs.org/de/docs/latest/tutorial/sandbox) is meant. It might be helpful to have an http file to reproduce the error. Or which setup is used (use of wsl or remote developmemnt, use of special CLI parameters e.g. --user-data-dir).

**Comment by AnWeber** [comment]
Needs more information.
