### ISSUE TITLE
Websocket cached one request (BUG)

### ISSUE THREAD

**Issue by bikevit2008** [httpyac/httpyac.github.io#60]
Hello! Your product comforable and useful for me, but i found bug.
When i use some same requests, after a little bit time, send changed request or another request, old request cached and sends for all tests(requests). I can fix it only by deleting extension and newly install it.
This behavior uncomfortable, please give me solution or fix

Demonstration this problem on my Youtube
https://www.youtube.com/watch?v=2AveinGVvyw

**Comment by AnWeber** [comment]
Uninstallation should not be necessary. With `httpyac.reset` you can actually reset all caches. I guess that the test explorer is not updated, so simply refreshing the explorer (refresh symbol) could be enough.

![image](https://user-images.githubusercontent.com/13434739/201730631-29cf0b23-f362-4c2e-b1c1-35b9349b081b.png)

I don't quite understand yet what exactly is happening in your video, I'll try to recreate it on my end once locally.

**Comment by bikevit2008** [comment]
I tried reset, it doesn't solve my problem.
In video i show code for my tests, and when i start set_game_settings code
`        let req = {
            route: 'game/set_game_settings',
            payload: {
                id: 'test122223',
                key: 'dfghjkPOIUY0987656321',
                doc: new_doc
            }
        }
        websocketClient.send(JSON.stringify(req));
`
I got sent request for set_spawn_zone
`
        let req = {
            route: 'system/set_spawn_zones',
            payload: {
                id: 'test122223',
                key: 'dfghjkPOIUY0987656321',
                doc: new_doc
            }
        }
        websocketClient.send(JSON.stringify(req));
`
So, i start one test, but i get start for another test

**Comment by AnWeber** [comment]
@bikevit2008 It ended up being a silly mistake, and I was lucky that I used an identical file for the test. The cause was that the unique Id for the individual http regions was only unique per file. As a result, however, the first TestItem with the same Id was always executed. I will release fix with v5.8.2

**Comment by bikevit2008** [comment]
![screenshot](https://user-images.githubusercontent.com/6545120/202917281-9c22defe-c219-41c4-9e2c-ac2c9c86f3e5.PNG)
Here u can see, i modified my test, but it sends cached old request, could you fix it?

**Comment by AnWeber** [comment]
@bikevit2008 I cannot currently reproduce the problem. Currently, my changes are applied directly and the correct file is executed.Could you please describe your setup in detail. Do you still use the execution via TestController? Does the problem also occur when using CodeLens directly or the `httpyac.send` command?

**Comment by bikevit2008** [comment]
@AnWeber Yep, from TestController, httpyac.send i can found keybinding doesn't work, CodeLens directly how to do it?

**Comment by bikevit2008** [comment]
![snap](https://user-images.githubusercontent.com/6545120/204339738-62a884af-5b0a-4366-a32a-e51a980ec60e.PNG)

**Comment by bikevit2008** [comment]
But it was content 'game/set_game_settings', i modified it to 'game/set_game_defaults', and it cached old request

**Comment by AnWeber** [comment]
I have reproduced it. It was now my 3rd attempt that I looked at it and the difference was that now I did not test it during debugging. It does not occur there. But in the releasing version it does.

**Comment by AnWeber** [comment]
Please retest with v6.0.0. I changed some logic in test runner.
