### ISSUE TITLE
Special formatter for .http files

### ISSUE THREAD

**Issue by bikevit2008** [httpyac/httpyac.github.io#61]
Hello!:)
I think this extension will be better, if you will add special formatter for files with .http type.
Now, i can use js formatter, but it do all files invalid (red), and i want to know which red show, really error or js validation error

**Comment by AnWeber** [comment]
No, there is no formatter at the moment. To implement this feature a LSP would be needed. See issue AnWeber/vscode-httpyac#101. A PR for this feature is welcome, but it needs some free time.
