### ISSUE TITLE
The SpaceX GraphQL Example Throws Application Error

### ISSUE THREAD

**Issue by saikatsgupta** [httpyac/httpyac.github.io#65]
The SpaceX GraphQL Example Doesn't Work (Throws Application Error - HTTP/1.1 503 - Service Unavailable).
There is an open issue in that repo: https://github.com/SpaceXLand/api/issues/241 

```html
<!DOCTYPE html>
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <title>Application Error</title>
  <style media="screen">
    html,
    body,
    iframe {
      margin: 0;
      padding: 0;
    }

    html,
    body {
      height: 100%;
      overflow: hidden;
    }

    iframe {
      width: 100%;
      height: 100%;
      border: 0;
    }
  </style>
</head>

<body>
  <iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
</body>

</html>
```

**Comment by AnWeber** [comment]
Hi, the examples are not always up to date. I don't have an automated test that checks the correctness. Cool that you take care of it.
I would just add your example as extra test file. Those are mostly then the test files I click through when I do updates. But for graphql I rely mostly on my [simple unit test](https://github.com/AnWeber/httpyac/blob/main/src/httpYacApi.spec.ts#L198).

**Comment by AnWeber** [comment]
I integrated the new service as default example. Thanks

**Comment by saikatsgupta** [comment]
Thanks, @AnWeber for this great tool.

**Comment by AnWeber** [comment]
You are welcome:-)
