### ISSUE TITLE
Failed example code snippet embeds in `variables.html`

### ISSUE THREAD

**Issue by myfonj** [httpyac/httpyac.github.io#73]
Some snippets in https://httpyac.github.io/guide/variables.html#examples fail to render correctly:

![image](https://github.com/httpyac/httpyac.github.io/assets/1761395/da98cd59-1759-4cd3-b4dc-19423563766d)

https://github.com/httpyac/httpyac.github.io/blob/c89ccb66b49a799f55298005d1b235695ed8ab70/docs/guide/variables.md?plain=1#L180-L203

**Comment by AnWeber** [comment]
thanks for the hint. The missing new line before the code import is causing this issue. Added more empty lines.
