### ISSUE TITLE
Unreadable tip parts in documentation

### ISSUE THREAD

**Issue by LeDevNovice** [httpyac/httpyac.github.io#74]
Hello guys,

I was reading the documentation of the project at https://httpyac.github.io/guide/request.html and I found, as you can see in the screen, that the "TIP" box are not really readable in dark theme version because of an insufficient contrast.

I was trying to see in the project the markdown part that seems to be here `::: tip The HTTP version is optional. But in this guide I have always added it because of syntax highlighting :::` and in my opinion there is a need for change in the value of the color variables --vp-c-brand-1: #777271 and --vp-c-brand-soft: #DDD7D3 in your custom.css file

![image](https://github.com/httpyac/httpyac.github.io/assets/68811343/c2de2676-a4bc-4479-a65d-5444eca7254b)

**Comment by AnWeber** [comment]
Always the lovers of the dark theme. You have to take the light theme:-) I changed the vb-c-brand-soft color in the dark theme. Thanks for your hint.
