### ISSUE TITLE
<code> tags not visible in dark mode

### ISSUE THREAD

**Issue by onestay** [httpyac/httpyac.github.io#75]
`<code></code>` tags are not visible when the site is in dark mode. In light mode everything looks good.
![image](https://github.com/httpyac/httpyac.github.io/assets/17146830/9433fa88-0c46-4362-99ba-138e4cf9f518)
![image](https://github.com/httpyac/httpyac.github.io/assets/17146830/0e993c11-afaf-4679-a660-b3086cbd758b)

Browser: Firefox 123.0.1
OS: Arch Linux

**Comment by AnWeber** [comment]
Thanks for the tip. Unfortunately, I am a light theme user, that's why I don't see these bugs so quickly:-)
