### ISSUE TITLE
Use metadata in scripts

### ISSUE THREAD

**Issue by tlunsfordCXP** [httpyac/httpyac.github.io#77]
In my "before" and "after" scripts, I'd like log metadata such as title or description, something like this:

```
{{
    console.log('BEGIN ' + @description);
}}

{{+after
    console.log('AFTER ' + @description);
}}
```

I would put the above at the beginning of a .http file, or even better, would like to be able to reference it for reusability.

Is this doable? I haven't found a way to get to such metadata for logging to console.

**Comment by AnWeber** [comment]
use [httpRegion](https://httpyac.github.io/guide/scripting.html#access-to-variables)
```
# @name json
GET https://httpbin.org/json

{{
  console.info(httpRegion.metaData.name);
}}
```

The easiest way to implement it in general would be to use a plugin and register an interceptor
> httpyac.config.cjs
```js
module.exports = {
  configureHooks: function (api) {
    api.hooks.execute.addInterceptor({
      id: '#77',
      beforeLoop(hookContext) {
        const context = hookContext.args[0];
        context?.scriptConsole?.info("Before " + context.httpRegion.metaData.name);
        return true;
      },
      afterLoop(hookContext) {
        const context = hookContext.args[0];
        context?.scriptConsole?.info("After " + context.httpRegion.metaData.name);
        return true;
      },

    });
  }
}
```

**Comment by tlunsfordCXP** [comment]
This is great, thank you! Some mixed results...

I was able to use regions in a single file, but it seems odd that the "before" uses `{{@request` and the "after" uses `{{+after`. Is there a more symmetrical pairing that has the metadata available available in both places?

The interceptor isn't working for me. I do have config file `httpyac.config.js` that works for things like disabling `cookieJarEnabled`. I've tried different types of hooks there in the past and they just don't seem to hit. How would I even begin debugging those hooks? (FWIW, I'm very experienced in development, just not so much in nodejs and related.)

**Comment by tlunsfordCXP** [comment]
Ugh... I just realized that `{{` for the individual request hits before global `{{@request`, so my logging sequence gets weird. But global `{{` hits before variables are replaced, so `undefined` gets logged. (I found the [diagram](https://httpyac.github.io/guide/scripting.html#events) in the scripting documentation, which helped to understand things.) 

I'm hoping that sorting out interceptors will help to solve this. 🤞

**Comment by AnWeber** [comment]
How would I even begin debugging those hooks?

Use.javascript debugger cli in vscode + httpyac in command line.
https://httpyac.github.io/guide/scripting.html#how-to-debug-scripts

**Comment by tlunsfordCXP** [comment]
This is helpful, thank you!

**Comment by tlunsfordCXP** [comment]
Soon I would like to help to pull together these tidbits of information into the documentation. Something that would help would to be able to label issues in the repo that we can reference. We would need some label definitions, such as "ForDocumentation" meaning that the conversation includes information that we want to capture in the documentation. This would also make it easier to find things that aren't yet in the formal documentation, especially if additional labels were included.

What do you think about this?

**Comment by tlunsfordCXP** [comment]
Sounds good. It seems that I don't have the privileges to be able to add labels.
